### ISSUE TITLE
FCC Unwanted Caller Database

### ISSUE THREAD

**Issue by adamgoldberg** [POSSA/Caller-ID-Superfecta#265]
The FCC is now publishing a summary of consumer complaints about robocalls/unwanted telemarketing, see https://consumercomplaints.fcc.gov/hc/en-us/articles/205239443-Data-on-Unwanted-Calls and https://consumercomplaints.fcc.gov/hc/theme_assets/513073/200051444/Telemarketing_RoboCall_Weekly_Data100115-102015.csv.

If I wanted to write some code that had the effect of either directing those calls directly to voicemail, or something, would Superfecta be an ok place to do that?  Maybe not, but can someone point me in the right direction?

Maybe a good thing to do would be to load the blacklist from the FCC's list?  (That's certainly not Superfecta).  Thanks!

(Is there another way to email this group without creating an "issue?"  I'm not sure this is an issue.  Sorry.)

**Comment by lgaetz** [comment]
It would work, but the spam interception aspects of Superfecta have not been well maintained, so that  would have to be fixed before effort was put into making the FCC list work. My gut feeling is that implementing the robocall list would best be done independently of Superfecta.

Creating issues here for discussion is fine, and even preferable for most things. If you have a matter you need to discuss privately, you can email either me or @tm1000 via the email address on our profiles.

**Comment by adamgoldberg** [comment]
Ok, well, understanding that this is outside of superfecta, do ya think that loading the blacklist from the FCC's list would be the best way to deal with this?  (Or, hah, alternately, what other group of Asterisk developers I should be bothering :) )

**Comment by lgaetz** [comment]
There is a conversation here that will reach a wider audience and might result in some ideas:
http://community.freepbx.org/t/fcc-robocall-list/31573

**Comment by adamgoldberg** [comment]
Thx.  That's a better place for this discussion, I suspect!
